#!/bin/bash

if ps ax | grep -v grep | grep "/home/alan/streamlit/streamlit" > /dev/null
then
    exit
else
    cd /home/alan/streamlit
    source venv/bin/activate
    streamlit run app.py &
fi

exit

